checkpoint_path: "D:/Image_Captioning_COCO/logs/train/20250811-095131/caption_model_20epochs.pth"

save_dir: "./logs"

data:
  image_dir: "./test_samples"
  ann_path: null

transform:
  resize: [128, 128]
  to_tensor: true
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

dataloader:
  batch_size: 16
  shuffle: false
  num_workers: 4
  pin_memory: true
  padding_value: 0

max_len: 20