# train.yaml

num_epochs: 10
print_every: 1
save_every: 5
device: cuda  

optimizer:
  type: Adam
  lr: 0.001
  weight_decay: 0.0001

scheduler:
  type: StepLR
  step_size: 50
  gamma: 0.5

criterion: 
  type: CrossEntropyLoss  
  ignore_idx: 0 

save_dir: ./logs

checkpoint_path: D:/Image_Captioning_COCO/logs/train/20250809-205742/caption_model_10epochs.pth
history_path: D:/Image_Captioning_COCO/logs/train/20250809-205742/history.json

misc:
  clip_grad_norm: 5
