# train.yaml
num_epochs: 10
print_every: 1
save_every: 2

transform:
  resize: [128, 128]
  to_tensor: true
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

dataloader:
  batch_size: 16
  shuffle: true
  num_workers: 4
  pin_memory: true
  padding_value: 0

data:
  image_dir: "./coco_10p/train2017"
  ann_path: "./coco_10p/annotations/captions_train2017.json"

optimizer:
  type: Adam
  lr: 0.001
  weight_decay: 0.0001

scheduler:
  type: StepLR
  step_size: 50
  gamma: 0.5

criterion: 
  type: CrossEntropyLoss  
  ignore_idx: 0 

save_dir: ./logs

checkpoint_path: "D:/Image_Captioning_COCO/logs/train/20250811-162536/caption_model_70epochs.pth"
history_path: "D:/Image_Captioning_COCO/logs/train/20250811-162536/history.json"

misc:
  clip_grad_norm: 5
